yeti-platform/yeti-feeds-frontend

- src/components/Navbar.vue
- src/router/index.js
- src/views/EditGroup.vue
- src/views/GroupAdmin.vue
> Group admin

- src/views/UserProfile.vue
> User permissions matrix

- src/components/RelatedObjects.vue
- src/views/EntityDetails.vue
- src/views/ObservableDetails.vue
Fixes #66 
Example of new view:
> Show more than one hops in tables

- src/definitions/observableDefinitions.js
This PR implements https://github.com/yeti-platform/yeti/issues/867 for yeti frontend
> Add docker image observable

- src/definitions/observableDefinitions.js
This PR adds frontend support for user agent observable type as requested by https://github.com/yeti-platform/yeti/issues/869
> Feat: Add user agent observable type

- src/views/Login.vue
Backend PR: https://github.com/yeti-platform/yeti/pull/925
> Fix: OIDC login button

- src/definitions/observableDefinitions.js
> Support IBAN & BIC observables

- src/components/ObjectList.vue
- src/definitions/dfiqDefinitions.js
- src/definitions/entityDefinitions.js
- src/definitions/indicatorDefinitions.js
- src/views/DFIQSearch.vue
- src/views/EntitySearch.vue
- src/views/IndicatorSearch.vue
- src/views/ObjectDetails.vue
Wait until https://github.com/yeti-platform/yeti-feeds-frontend/pull/151 is merged
> Add controls for tagging Indicators

- src/components/ObjectFields.vue
- src/definitions/indicatorDefinitions.js
Also adds the same density to all components
> New field type: option-custom

- src/components/TaskList.vue
- src/views/ExportList.vue
- src/views/ExportTemplates.vue
Fixes https://github.com/yeti-platform/yeti/issues/1034
Fixes https://github.com/yeti-platform/yeti-feeds-frontend/issues/127
> Export fixes

- src/components/EditLink.vue
- src/components/EntitySelector.vue
- src/components/LinkObject.vue
- src/definitions/linkSuggestions.js
> Guide user through selecting the right links

- src/components/DirectNeighbors.vue
- src/components/EditLink.vue
- src/components/YetiMarkdown.vue
- src/definitions/observableDefinitions.js
- src/views/ObjectDetails.vue
Introduce a DirectNeighbors vue component for neighbors that are one hop away. This provides more details and more specialized UI. (pending https://github.com/yeti-platform/yeti/pull/1067/files)
* Ability to filter through neighbors
* Ability to sort neighbors
* Inline markdown view of link descriptions
> Feature: Enhanced direct neighbors view

- src/components/DirectNeighbors.vue
- src/components/LinkObservables.vue
- src/components/ObjectList.vue
- src/definitions/dfiqDefinitions.js
- src/definitions/entityDefinitions.js
- src/definitions/indicatorDefinitions.js
- src/definitions/observableDefinitions.js
- src/views/DFIQSearch.vue
- src/views/EntitySearch.vue
- src/views/IndicatorSearch.vue
- src/views/ObservableDetails.vue
* [Fix overflow when names / values are too long](https://github.com/yeti-platform/yeti-feeds-frontend/pull/182/commits/0522d1faf81fdabd465b430c97d0a9ac93907d21)
* [Add more controls to observable linking](https://github.com/yeti-platform/yeti-feeds-frontend/pull/182/commits/79f35be94a752a38d7450ada438b5573f10a738e)
* [Fix width in search tables](https://github.com/yeti-platform/yeti-feeds-frontend/pull/182/commits/427a7ca68244ea8ee34872593d768b9036369006)
* [Tab memory navigation](https://github.com/yeti-platform/yeti-feeds-frontend/pull/182/commits/17bb8b28ccda396c59b6163f9c4b2c87b7d4c24c)
* [Better handling of long observable values](https://github.com/yeti-platform/yeti-feeds-frontend/pull/182/commits/d84c7e25ae24594b61ce51caaa8d30ab0b6c0bec)
* [Use …
> Various UI tweaks

- src/components/DFIQ/EditDFIQObject.vue
- src/components/DFIQTree.vue
- src/components/YetiDFIQApproachTemplate.vue
* [Fix edit link to indicators](https://github.com/yeti-platform/yeti-feeds-frontend/commit/f9e3f1871cff8011fbe94eeb33f7941d71482668)
* [Save indicators upon creation](https://github.com/yeti-platform/yeti-feeds-frontend/commit/16940507bd725bf8e2f429d51ddf59500e833361)
> Minor DFIQ fixes

- src/components/DFIQ/EditDFIQObject.vue
- src/components/DFIQTree.vue
- src/definitions/dfiqDefinitions.js
* Placeholders and hints in form
* Ability to directly edit approaches from the tree view
* More user-friendly error reporting
> Improvements over DFIQ question editing & guidance

- src/definitions/entityDefinitions.js
Add first / last seen columns in list view and make them editable in object view
> Update campaign view

- src/components/DirectNeighbors.vue
- src/components/EntitySelector.vue
- src/components/ObjectList.vue
- src/views/TagsAdmin.vue
Adds loading animations to server-side data tables
> Add loading indicators

- src/definitions/entityDefinitions.js
> Make intrusion set aliases editable

- src/views/AnalyticsList.vue
> Analytics display cleanup

- src/definitions/entityDefinitions.js
- src/definitions/linkSuggestions.js
This PR depends on the merge of this [Yeti PR](https://github.com/yeti-platform/yeti/pull/1168)
> Update related observables count to total links

- src/definitions/observableDefinitions.js
Add container image definitions to display all fields in detailed view
> Add container image definition

- .github/workflows/build.yaml
- src/components/EditObject.vue
- src/components/GraphObjects.vue
- src/components/Timeline.vue
- src/views/ObjectDetails.vue
- src/views/ObservableDetails.vue
Added a timeline view to object details page
> Timeline view

- src/definitions/observableDefinitions.js
This PR adds frontend definitions for AuthSecret observable.
> Add AuthSecret definitions

- package-lock.json
- package.json
- src/plugins/vuetify.ts
- src/views/ObservableDetails.vue
- src/views/ObservableSearch.vue
This PR adds support to render context as a tree view. The screenshot below highlights current implementation and changes:
> Context Tree View

- src/components/DFIQTree.vue
> Display DFIQ tags in DFIQ tree view

- src/views/UserProfile.vue
Also nicer password change box
> Fix patching role

- src/components/DFIQ/DFIQApproaches.vue
- src/components/DFIQ/DFIQTree.vue
- src/components/DFIQ/EditDFIQObject.vue
- src/components/DFIQ/YetiDFIQApproachTemplate.vue
- src/plugins/vuetify.ts
- src/router/index.ts
- src/store/app.ts
- src/views/ObjectDetails.vue
- src/views/ObservableDetails.vue
* Improvements in the way DFIQ quesitons / approaches are displayed
* Fixed bug that stopped approaches form being listeed in the DFIQ Question details
* Page titles!!
> Quality of life changes & bugfixes
